spring:
  datasource:
#        url: jdbc:mysql://localhost:3306/aptech_forums?createDatabaseIfNotExist=true
#        username: root
#        password:
    url: postgres://ajibecqpnajisk:2ca0a101a0b902cabd1a5ed94b1071f24d46954b30e36c1df545a54343579d10@ec2-44-206-197-71.compute-1.amazonaws.com:5432/de4v9f51953m50
    username: ajibecqpnajisk
    password: 2ca0a101a0b902cabd1a5ed94b1071f24d46954b30e36c1df545a54343579d10
    driverClassName: org.postgresql.Driver
  mail:
    port: 587
    host: smtp.gmail.com
    username: forum.fptaptech@gmail.com
    password: rmdiupuwvzfvguon
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      starttls:
        enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 572511665932-lam11rsjg0f9hlfmjkc5mri9ndm33u2a.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: 31c2e8628954c21966c1
            clientSecret: b361c098f56d45e7df4149c1cce6639b65eaac89
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
allowed:
  origin: http://localhost:3000
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,https://forums-aptech.herokuapp.com
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://forums-demo.vercel.app/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect