spring:
  jackson:
    time-zone: Vietnam/Ho_Chi_Minh
  datasource:
    url: jdbc:mysql://34.87.38.9/forum_aptech?createDatabaseIfNotExist=true
    username: root
    password: Dduc_NV0712
#     url: jdbc:mysql://localhost:3306/forum_aptech?createDatabaseIfNotExist=true
#     username: root
#     password:
#     url: jdbc:mysql://appcuaduc:asia-southeast1:forums-db
#     username: root
#     password:
#    url: jdbc:mysql://us-east.connect.psdb.cloud/forums_t2009m1_db?sslMode=VERIFY_IDENTITY
#    username: ykx2en5o1rqd9e60arbt
#    password: pscale_pw_dW1Cs3MsLqT2fVmdxz3hNAXqfXPsZGX0G0wrM5NbKTV
#     url: jdbc:postgresql://free-tier8.aws-ap-southeast-1.cockroachlabs.cloud:26257/defaultdb?options=--cluster%3Dfancy-dragon-2874&password=qP6VlDJWhxsoThc7ttmW0g&sslmode=verify-full&user=dducnv
#     username: dducnv
#     password: qP6VlDJWhxsoThc7ttmW0g
#     driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    port: 587
    host: smtp.gmail.com
    username: forum.fptaptech@gmail.com
    password: rmdiupuwvzfvguon
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      starttls:
        enable: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 572511665932-lam11rsjg0f9hlfmjkc5mri9ndm33u2a.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: 31c2e8628954c21966c1
            clientSecret: b361c098f56d45e7df4149c1cce6639b65eaac89
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
allowed:
  origin: http://localhost:3000
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://forums-demo.vercel.app/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect